# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62ea5d62f0f695d4a6a9824c063f9ca82ecf066ffcd4be42819809e637b0d1ee08dccdd79480c1eebc09f6e3adce9ddde64afc0a1080e9671914560307a1c6d8

test:
  secret_key_base: 42fd075a8fd852d3c257eacd249bc92e05d52320ae1a058609c2afe5886269f721453e10a40c3b2e57a049a79326b500ff2b4e94f5c75186aa4ed00f5dacbda3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
